proxies:
  - name: "VLESS-WS-1"
    type: vless
    server: 92.223.76.20  # Первый IP
    port: 443
    uuid: b20f0323-eb7a-4765-9329-4d2992d49900
    tls: true
    network: wss  # Используем wss для безопасного соединения
    ws-opts:
      path: "/bb"  # Путь, обновлен на "bb"
      headers:
        Host: "sip.sefc.space"  # Маскировка
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"  # Строка вместо массива
      sni: "."  # Использование SNI в виде точки "."
    allowInsecure: true  # Разрешить небезопасные соединения (обход проверки сертификатов)
    encryption: none  # Без дополнительного шифрования (если требуется)
    fingerprint: "chrome"  # Использование отпечатка для имитации Chrome (если сервер требует)

  - name: "VLESS-WS-2"
    type: vless
    server: 93.123.17.151  # Второй IP
    port: 443
    uuid: b20f0323-eb7a-4765-9329-4d2992d49900
    tls: true
    network: wss  # Используем wss для безопасного соединения
    ws-opts:
      path: "/bb"  # Путь, обновлен на "bb"
      headers:
        Host: "sip.sefc.space"  # Маскировка
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"  # Строка вместо массива
      sni: "."  # Использование SNI в виде точки "."
    allowInsecure: true  # Разрешить небезопасные соединения (обход проверки сертификатов)
    encryption: none  # Без дополнительного шифрования (если требуется)
    fingerprint: "chrome"  # Использование отпечатка для имитации Chrome (если сервер требует)

proxy-groups:
  - name: "Auto-Select"
    type: select
    proxies:
      - "VLESS-WS-1"
      - "VLESS-WS-2"
