proxies:
  - name: "VLESS-WS-1"
    type: vless
    server: 92.223.76.20  # Первый IP
    port: 443
    uuid: b20f0323-eb7a-4765-9329-4d2992d49900
    tls: true
    network: ws
    ws-opts:
      path: "/bb"  # Пример пути, замените, если нужно
      headers:
        Host: "sip.sefc.space"  # Маскировка
        User-Agent:
          - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      sni: "."  # Использование точки для SNI

  - name: "VLESS-WS-2"
    type: vless
    server: 93.123.17.151  # Второй IP
    port: 443
    uuid: b20f0323-eb7a-4765-9329-4d2992d49900
    tls: true
    network: ws
    ws-opts:
      path: "/bb"  # Пример пути, замените, если нужно
      headers:
        Host: "sip.sefc.space"  # Маскировка
        User-Agent:
          - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      sni: "."  # Использование точки для SNI

proxy-groups:
  - name: "Auto-Select"
    type: select
    proxies:
      - "VLESS-WS-1"
      - "VLESS-WS-2"
